version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'elaparato'
      MYSQL_USER: 'usr'
      MYSQL_PASSWORD: 'pwd-usr'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3380:3306'
    expose:
      - '3306'
   