server:
  port: 8181

spring:
  application:
    name: keycloak-admin

elaparato:
  keycloak:
    serverUrl: http://localhost:8080
    realm: el-aparato-santiago-hernandez
    clientId: administracion-usuarios
    clientSecret: Umweb60cvZj21GcdBlXlWRPE5r2SikdF
